services:
  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    ports:
      - "8191:8191"
    environment:
      TZ: Asia/Hong_Kong
      LOG_LEVEL: info
      LOG_FILE: /config/flaresolverr.log
      LOG_HTML: true
      CAPTCHA_SOLVER: none
      PROXY_URL: socks5h://microwarp:1080
    volumes:
      - flaresolverr:/config
    networks:
      - flaresolverr
      - apinetwork
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G

networks:
  flaresolverr:
    name: flaresolverr
  apinetwork:
    name: apinetwork

volumes:
  flaresolverr:
    name: flaresolverr
